
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 17 2025 05:33:13

// Verification Directory fv/synth_wrapper 

module alu(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158;
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_158), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_157), .Q (result[2]));
  sky130_fd_sc_hd__nand3_1 g8767(.A (n_153), .B (n_154), .C (n_141), .Y
       (n_158));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (n_155), .Q (carry));
  sky130_fd_sc_hd__nand2_1 g8769(.A (n_156), .B (n_139), .Y (n_157));
  sky130_fd_sc_hd__nand2_1 g8770(.A (n_4), .B (n_59), .Y (n_156));
  sky130_fd_sc_hd__a41oi_2 g8771(.A1 (n_150), .A2 (n_147), .A3 (n_148),
       .A4 (n_135), .B1 (n_60), .Y (n_155));
  sky130_fd_sc_hd__a21o_1 g8772(.A1 (n_142), .A2 (n_110), .B1 (n_126),
       .X (n_154));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_151), .Q (result[1]));
  sky130_fd_sc_hd__nand2_1 g8774(.A (n_152), .B (n_130), .Y (n_153));
  sky130_fd_sc_hd__nand4_1 g8775(.A (n_149), .B (n_132), .C (n_3), .D
       (n_131), .Y (n_152));
  sky130_fd_sc_hd__o21ai_1 g8776(.A1 (n_60), .A2 (n_138), .B1 (n_134),
       .Y (n_151));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_140), .Q (result[0]));
  sky130_fd_sc_hd__nor2_1 g8779(.A (n_145), .B (n_144), .Y (n_150));
  sky130_fd_sc_hd__clkinv_1 g8780(.A (n_146), .Y (n_149));
  sky130_fd_sc_hd__nand3_1 g8781(.A (n_112), .B (n_103), .C (n_117), .Y
       (n_148));
  sky130_fd_sc_hd__nand4_1 g8782(.A (n_117), .B (n_103), .C (n_70), .D
       (n_89), .Y (n_147));
  sky130_fd_sc_hd__nand2_1 g8783(.A (n_137), .B (n_90), .Y (n_146));
  sky130_fd_sc_hd__nor2_1 g8784(.A (n_137), .B (n_123), .Y (n_145));
  sky130_fd_sc_hd__nor2_1 g8785(.A (n_123), .B (n_3), .Y (n_144));
  sky130_fd_sc_hd__inv_2 g8786(.A (n_142), .Y (n_143));
  sky130_fd_sc_hd__a21oi_2 g8787(.A1 (n_128), .A2 (a[3]), .B1 (n_133),
       .Y (n_141));
  sky130_fd_sc_hd__nand3_1 g8788(.A (n_127), .B (n_116), .C (n_125), .Y
       (n_140));
  sky130_fd_sc_hd__and4_1 g8789(.A (n_129), .B (n_114), .C (n_120), .D
       (n_118), .X (n_139));
  sky130_fd_sc_hd__xnor2_1 g8790(.A (n_70), .B (n_117), .Y (n_138));
  sky130_fd_sc_hd__nand3_2 g8791(.A (n_119), .B (n_136), .C (n_111), .Y
       (n_142));
  sky130_fd_sc_hd__nand2_1 g8792(.A (n_124), .B (n_62), .Y (n_136));
  sky130_fd_sc_hd__a21oi_1 g8793(.A1 (n_8), .A2 (n_103), .B1 (n_2), .Y
       (n_135));
  sky130_fd_sc_hd__nand4_1 g8795(.A (n_71), .B (n_73), .C (n_15), .D
       (n_20), .Y (n_137));
  sky130_fd_sc_hd__o2111a_1 g8796(.A1 (n_65), .A2 (n_82), .B1 (n_113),
       .C1 (n_101), .D1 (n_6), .X (n_134));
  sky130_fd_sc_hd__o211ai_2 g8797(.A1 (n_16), .A2 (n_100), .B1 (n_92),
       .C1 (n_115), .Y (n_133));
  sky130_fd_sc_hd__nand3_1 g8798(.A (n_117), .B (n_89), .C (n_70), .Y
       (n_132));
  sky130_fd_sc_hd__nand2_1 g8799(.A (n_112), .B (n_117), .Y (n_131));
  sky130_fd_sc_hd__nor2_1 g8801(.A (n_60), .B (n_103), .Y (n_130));
  sky130_fd_sc_hd__nand2_1 g8802(.A (n_121), .B (n_26), .Y (n_129));
  sky130_fd_sc_hd__o2111ai_1 g8803(.A1 (n_95), .A2 (n_58), .B1 (n_79),
       .C1 (n_82), .D1 (n_93), .Y (n_128));
  sky130_fd_sc_hd__o2bb2ai_1 g8804(.A1_N (n_82), .A2_N (n_98), .B1
       (n_24), .B2 (b[0]), .Y (n_127));
  sky130_fd_sc_hd__nand3_1 g8805(.A (n_103), .B (n_90), .C (n_59), .Y
       (n_126));
  sky130_fd_sc_hd__o221ai_1 g8806(.A1 (n_11), .A2 (n_76), .B1 (n_24),
       .B2 (n_58), .C1 (n_122), .Y (n_125));
  sky130_fd_sc_hd__o2bb2ai_2 g8807(.A1_N (n_19), .A2_N (n_104), .B1
       (n_19), .B2 (n_104), .Y (n_124));
  sky130_fd_sc_hd__inv_2 g8808(.A (n_103), .Y (n_123));
  sky130_fd_sc_hd__a21oi_1 g8809(.A1 (n_65), .A2 (b[0]), .B1 (n_95), .Y
       (n_122));
  sky130_fd_sc_hd__o221ai_1 g8810(.A1 (n_15), .A2 (n_81), .B1 (n_14),
       .B2 (n_27), .C1 (n_82), .Y (n_121));
  sky130_fd_sc_hd__nand2_1 g8811(.A (n_109), .B (n_15), .Y (n_120));
  sky130_fd_sc_hd__o21a_1 g8812(.A1 (n_58), .A2 (n_45), .B1 (n_99), .X
       (n_119));
  sky130_fd_sc_hd__o2111ai_1 g8813(.A1 (n_15), .A2 (n_58), .B1 (n_77),
       .C1 (n_67), .D1 (n_86), .Y (n_118));
  sky130_fd_sc_hd__a31oi_1 g8814(.A1 (n_57), .A2 (n_94), .A3 (n_24),
       .B1 (n_97), .Y (n_116));
  sky130_fd_sc_hd__o2111ai_1 g8815(.A1 (a[3]), .A2 (n_58), .B1 (n_78),
       .C1 (n_91), .D1 (n_94), .Y (n_115));
  sky130_fd_sc_hd__a21oi_1 g8817(.A1 (n_83), .A2 (n_14), .B1 (n_102),
       .Y (n_114));
  sky130_fd_sc_hd__o32a_1 g8818(.A1 (n_27), .A2 (n_12), .A3 (n_22), .B1
       (n_23), .B2 (n_84), .X (n_113));
  sky130_fd_sc_hd__nand2_4 g8819(.A (n_107), .B (n_108), .Y (n_117));
  sky130_fd_sc_hd__inv_2 g8820(.A (n_105), .Y (n_112));
  sky130_fd_sc_hd__o21ai_1 g8821(.A1 (n_26), .A2 (n_81), .B1 (n_82), .Y
       (n_109));
  sky130_fd_sc_hd__nand2_2 g8822(.A (n_71), .B (n_41), .Y (n_108));
  sky130_fd_sc_hd__nand2_2 g8823(.A (n_96), .B (n_20), .Y (n_107));
  sky130_fd_sc_hd__nand2_1 g8824(.A (n_80), .B (n_69), .Y (n_106));
  sky130_fd_sc_hd__nand3_1 g8825(.A (n_70), .B (n_73), .C (n_15), .Y
       (n_105));
  sky130_fd_sc_hd__nand2_2 g8826(.A (n_71), .B (n_23), .Y (n_111));
  sky130_fd_sc_hd__o2bb2ai_2 g8827(.A1_N (n_15), .A2_N (n_73), .B1
       (n_15), .B2 (n_73), .Y (n_110));
  sky130_fd_sc_hd__nor3_1 g8828(.A (n_9), .B (n_75), .C (n_95), .Y
       (n_102));
  sky130_fd_sc_hd__o2111ai_1 g8829(.A1 (n_20), .A2 (n_58), .B1 (n_85),
       .C1 (n_68), .D1 (n_86), .Y (n_101));
  sky130_fd_sc_hd__o21a_1 g8830(.A1 (a[3]), .A2 (n_81), .B1 (n_82), .X
       (n_100));
  sky130_fd_sc_hd__nand4_1 g8831(.A (n_17), .B (n_42), .C (n_13), .D
       (n_20), .Y (n_99));
  sky130_fd_sc_hd__a21o_1 g8832(.A1 (n_81), .A2 (n_60), .B1 (n_62), .X
       (n_98));
  sky130_fd_sc_hd__o22ai_1 g8833(.A1 (n_24), .A2 (n_84), .B1 (n_27),
       .B2 (n_63), .Y (n_97));
  sky130_fd_sc_hd__nand2_2 g8834(.A (n_49), .B (n_46), .Y (n_104));
  sky130_fd_sc_hd__nand2_4 g8835(.A (n_87), .B (n_88), .Y (n_103));
  sky130_fd_sc_hd__inv_2 g8836(.A (n_71), .Y (n_96));
  sky130_fd_sc_hd__inv_2 g8837(.A (n_1), .Y (n_94));
  sky130_fd_sc_hd__nand2_1 g8838(.A (n_80), .B (n_16), .Y (n_93));
  sky130_fd_sc_hd__nand2_1 g8839(.A (n_83), .B (n_31), .Y (n_92));
  sky130_fd_sc_hd__nand2_1 g8840(.A (n_5), .B (n_9), .Y (n_91));
  sky130_fd_sc_hd__nand2_1 g8841(.A (n_85), .B (n_64), .Y (n_95));
  sky130_fd_sc_hd__nand2_2 g8844(.A (n_74), .B (n_31), .Y (n_88));
  sky130_fd_sc_hd__nand3_1 g8845(.A (n_54), .B (n_0), .C (a[3]), .Y
       (n_87));
  sky130_fd_sc_hd__nand2_4 g8847(.A (n_72), .B (n_15), .Y (n_90));
  sky130_fd_sc_hd__nor2_2 g8848(.A (n_15), .B (n_73), .Y (n_89));
  sky130_fd_sc_hd__inv_2 g8849(.A (n_84), .Y (n_83));
  sky130_fd_sc_hd__inv_2 g8850(.A (n_81), .Y (n_80));
  sky130_fd_sc_hd__or2_1 g8851(.A (n_16), .B (n_27), .X (n_79));
  sky130_fd_sc_hd__nand2_1 g8852(.A (n_53), .B (n_11), .Y (n_78));
  sky130_fd_sc_hd__o21a_1 g8853(.A1 (n_11), .A2 (n_42), .B1 (n_64), .X
       (n_86));
  sky130_fd_sc_hd__nor2_2 g8854(.A (n_66), .B (n_35), .Y (n_85));
  sky130_fd_sc_hd__nor2_1 g8855(.A (n_18), .B (n_66), .Y (n_77));
  sky130_fd_sc_hd__nand2_1 g8856(.A (n_52), .B (n_17), .Y (n_84));
  sky130_fd_sc_hd__nand2_2 g8857(.A (n_17), .B (n_61), .Y (n_82));
  sky130_fd_sc_hd__nand2b_4 g8858(.A_N (n_37), .B (n_52), .Y (n_81));
  sky130_fd_sc_hd__inv_1 g8859(.A (n_75), .Y (n_76));
  sky130_fd_sc_hd__inv_2 g8862(.A (n_73), .Y (n_72));
  sky130_fd_sc_hd__xnor2_1 g8863(.A (n_40), .B (n_11), .Y (n_69));
  sky130_fd_sc_hd__a21oi_1 g8864(.A1 (n_13), .A2 (n_31), .B1 (n_53), .Y
       (n_68));
  sky130_fd_sc_hd__a2bb2oi_1 g8865(.A1_N (n_24), .A2_N (n_12), .B1
       (b[0]), .B2 (n_41), .Y (n_67));
  sky130_fd_sc_hd__o2bb2ai_1 g8866(.A1_N (n_14), .A2_N (n_42), .B1
       (a[3]), .B2 (n_42), .Y (n_75));
  sky130_fd_sc_hd__nand2_1 g8868(.A (n_54), .B (n_0), .Y (n_74));
  sky130_fd_sc_hd__nand2_4 g8869(.A (n_50), .B (n_48), .Y (n_73));
  sky130_fd_sc_hd__nand2_4 g8870(.A (n_47), .B (n_44), .Y (n_71));
  sky130_fd_sc_hd__nand2_2 g8871(.A (n_51), .B (n_63), .Y (n_70));
  sky130_fd_sc_hd__clkinv_1 g8873(.A (n_63), .Y (n_62));
  sky130_fd_sc_hd__inv_2 g8875(.A (n_27), .Y (n_61));
  sky130_fd_sc_hd__clkinv_1 g8876(.A (n_60), .Y (n_59));
  sky130_fd_sc_hd__clkinv_1 g8878(.A (n_58), .Y (n_57));
  sky130_fd_sc_hd__nand2_1 g8880(.A (n_43), .B (b[0]), .Y (n_56));
  sky130_fd_sc_hd__nand2_1 g8882(.A (n_39), .B (n_42), .Y (n_55));
  sky130_fd_sc_hd__nand2_2 g8883(.A (op[2]), .B (op[1]), .Y (n_66));
  sky130_fd_sc_hd__nor2_1 g8884(.A (n_20), .B (n_10), .Y (n_65));
  sky130_fd_sc_hd__nor2_1 g8885(.A (b[3]), .B (n_26), .Y (n_64));
  sky130_fd_sc_hd__nand2_1 g8886(.A (a[0]), .B (b[0]), .Y (n_63));
  sky130_fd_sc_hd__nand2_2 g8887(.A (n_32), .B (op[1]), .Y (n_27));
  sky130_fd_sc_hd__or2_1 g8888(.A (op[2]), .B (op[1]), .X (n_60));
  sky130_fd_sc_hd__nand2_4 g8889(.A (n_42), .B (n_12), .Y (n_58));
  sky130_fd_sc_hd__nand2_1 g8890(.A (n_37), .B (n_42), .Y (n_51));
  sky130_fd_sc_hd__nand2_1 g8891(.A (n_33), .B (n_25), .Y (n_50));
  sky130_fd_sc_hd__nand2_1 g8892(.A (n_28), .B (a[1]), .Y (n_49));
  sky130_fd_sc_hd__nand2_1 g8893(.A (op[0]), .B (b[2]), .Y (n_48));
  sky130_fd_sc_hd__nand2_2 g8894(.A (n_34), .B (n_29), .Y (n_47));
  sky130_fd_sc_hd__nand2_1 g8895(.A (n_33), .B (b[3]), .Y (n_54));
  sky130_fd_sc_hd__nand2_1 g8896(.A (n_38), .B (b[1]), .Y (n_46));
  sky130_fd_sc_hd__nand2_1 g8897(.A (n_35), .B (n_22), .Y (n_45));
  sky130_fd_sc_hd__nand2_1 g8898(.A (op[0]), .B (n_30), .Y (n_44));
  sky130_fd_sc_hd__and2_1 g8899(.A (b[0]), .B (n_14), .X (n_53));
  sky130_fd_sc_hd__nor2_2 g8900(.A (op[1]), .B (n_32), .Y (n_52));
  sky130_fd_sc_hd__inv_2 g8904(.A (n_25), .Y (n_26));
  sky130_fd_sc_hd__inv_2 g8905(.A (b[2]), .Y (n_25));
  sky130_fd_sc_hd__clkinv_1 g8907(.A (n_43), .Y (n_24));
  sky130_fd_sc_hd__clkinv_1 g8908(.A (a[0]), .Y (n_43));
  sky130_fd_sc_hd__clkinv_4 g8909(.A (b[0]), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g8910(.A (n_40), .Y (n_41));
  sky130_fd_sc_hd__inv_2 g8911(.A (n_39), .Y (n_40));
  sky130_fd_sc_hd__clkinv_1 g8912(.A (a[1]), .Y (n_39));
  sky130_fd_sc_hd__inv_2 g8915(.A (n_22), .Y (n_23));
  sky130_fd_sc_hd__clkinv_1 g8916(.A (a[1]), .Y (n_22));
  sky130_fd_sc_hd__buf_6 g8920(.A (a[1]), .X (n_20));
  sky130_fd_sc_hd__inv_2 g8921(.A (a[1]), .Y (n_38));
  sky130_fd_sc_hd__inv_2 g8923(.A (n_37), .Y (n_19));
  sky130_fd_sc_hd__inv_4 g8924(.A (n_36), .Y (n_37));
  sky130_fd_sc_hd__inv_2 g8926(.A (op[0]), .Y (n_36));
  sky130_fd_sc_hd__inv_2 g8927(.A (n_34), .Y (n_35));
  sky130_fd_sc_hd__inv_2 g8928(.A (op[0]), .Y (n_34));
  sky130_fd_sc_hd__inv_2 g8929(.A (op[0]), .Y (n_33));
  sky130_fd_sc_hd__inv_2 g8932(.A (n_18), .Y (n_17));
  sky130_fd_sc_hd__inv_2 g8933(.A (op[0]), .Y (n_18));
  sky130_fd_sc_hd__inv_2 g8934(.A (op[2]), .Y (n_32));
  sky130_fd_sc_hd__inv_2 g8937(.A (b[3]), .Y (n_16));
  sky130_fd_sc_hd__inv_2 g8939(.A (a[3]), .Y (n_31));
  sky130_fd_sc_hd__inv_2 g8942(.A (n_14), .Y (n_15));
  sky130_fd_sc_hd__inv_2 g8947(.A (a[2]), .Y (n_14));
  sky130_fd_sc_hd__inv_2 g8950(.A (n_12), .Y (n_13));
  sky130_fd_sc_hd__clkinv_2 g8951(.A (b[1]), .Y (n_12));
  sky130_fd_sc_hd__clkinv_1 g8952(.A (b[1]), .Y (n_30));
  sky130_fd_sc_hd__clkbuf_1 g8953(.A (b[1]), .X (n_29));
  sky130_fd_sc_hd__inv_2 g8959(.A (n_10), .Y (n_11));
  sky130_fd_sc_hd__inv_2 g8960(.A (n_28), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g8961(.A (b[1]), .Y (n_28));
  sky130_fd_sc_hd__inv_2 fopt8973(.A (n_90), .Y (n_8));
  sky130_fd_sc_hd__o21a_1 g2(.A1 (n_7), .A2 (n_1), .B1 (n_106), .X
       (n_6));
  sky130_fd_sc_hd__nand3_1 g3(.A (n_11), .B (n_55), .C (n_56), .Y
       (n_7));
  sky130_fd_sc_hd__inv_2 g8974(.A (n_11), .Y (n_9));
  sky130_fd_sc_hd__nand2_1 g8975(.A (n_55), .B (n_56), .Y (n_5));
  sky130_fd_sc_hd__xnor2_1 g8976(.A (n_110), .B (n_143), .Y (n_4));
  sky130_fd_sc_hd__nand2b_1 g8979(.A_N (n_111), .B (n_89), .Y (n_3));
  sky130_fd_sc_hd__nor2b_1 g8980(.A (n_31), .B_N (n_74), .Y (n_2));
  sky130_fd_sc_hd__nand4b_1 g8981(.A_N (n_66), .B (n_37), .C (n_25), .D
       (n_16), .Y (n_1));
  sky130_fd_sc_hd__nand2b_1 g8983(.A_N (b[3]), .B (op[0]), .Y (n_0));
endmodule

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [2:0] op_reg;
  wire carry_reg_48, \result_reg[0]_36 , \result_reg[1]_37 ,
       \result_reg[2]_38 , \result_reg[3]_39 ;
  alu alu_design(.clk (clk), .rst_n (rst_n), .a (a_reg), .b (b_reg),
       .op (op_reg), .result ({\result_reg[3]_39 , \result_reg[2]_38 ,
       \result_reg[1]_37 , \result_reg[0]_36 }), .carry (carry_reg_48));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_39 ), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_38 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_36 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_48), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_37 ), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_2 \op_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op[0]), .Q (op_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op[2]), .Q (op_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (a[1]), .Q (a_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (a[0]), .Q (a_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op[1]), .Q (op_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (a[2]), .Q (a_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (a[3]), .Q (a_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (b[2]), .Q (b_reg[2]));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (b[1]), .Q (b_reg[1]));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (b[0]), .Q (b_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (b[3]), .Q (b_reg[3]));
endmodule

