
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 17 2025 03:12:53

// Verification Directory fv/synth_wrapper 

module alu(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_1, n_2, n_3, n_4, n_9, n_10, n_11;
  wire n_12, n_13, n_18, n_19, n_22, n_25, n_26, n_27;
  wire n_28, n_30, n_31, n_32, n_33, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_45, n_50, n_51, n_53, n_54;
  wire n_57, n_58, n_59, n_60, n_63, n_64, n_65, n_66;
  wire n_69, n_70, n_76, n_77, n_80, n_81, n_84, n_85;
  wire n_88, n_90, n_91, n_92, n_98, n_101, n_103, n_106;
  wire n_113, n_114, n_115, n_120, n_121, n_126, n_127, n_131;
  wire n_132, n_134, n_137, n_142, n_143, n_147, n_152, n_154;
  wire n_191, n_199, n_206, n_207, n_231, n_246, n_282, n_283;
  wire n_287, n_288, n_290, n_292, n_295, n_301, n_302, n_304;
  wire n_305, n_315, n_316, n_318, n_319, n_322, n_323, n_325;
  wire n_326, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_345, n_347, n_348, n_349;
  wire n_352, n_354, n_359, n_360, n_361, n_369, n_370, n_371;
  wire n_374, n_375, n_380, n_387, n_388, n_389, n_392, n_394;
  wire n_395, n_396, n_397, n_407, n_408, n_409, n_410, n_414;
  wire n_415, n_426, n_428, n_430, n_433, n_435, n_436, n_437;
  wire n_438, n_439, n_451, n_453, n_454, n_455, n_456, n_460;
  wire n_461, n_463, n_464, n_465, n_466, n_467, n_468, n_470;
  wire n_471, n_472, n_473, n_474, n_475, n_476, n_477, n_480;
  wire n_481, n_482, n_483;
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_454), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_290), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (n_456), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_152), .Q (result[1]));
  sky130_fd_sc_hd__nand2_1 g8914(.A (n_389), .B (n_131), .Y (n_154));
  sky130_fd_sc_hd__o21ai_2 g8916(.A1 (n_60), .A2 (n_142), .B1 (n_438),
       .Y (n_152));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_143), .Q (result[0]));
  sky130_fd_sc_hd__nand4_1 g8923(.A (n_387), .B (n_371), .C (n_332), .D
       (n_91), .Y (n_147));
  sky130_fd_sc_hd__nand3_1 g8928(.A (n_437), .B (n_115), .C (n_126), .Y
       (n_143));
  sky130_fd_sc_hd__xnor2_1 g8929(.A (n_332), .B (n_387), .Y (n_142));
  sky130_fd_sc_hd__nand2_1 g8935(.A (n_91), .B (n_132), .Y (n_137));
  sky130_fd_sc_hd__nand2_2 g8938(.A (n_387), .B (n_331), .Y (n_134));
  sky130_fd_sc_hd__inv_2 g8940(.A (n_474), .Y (n_132));
  sky130_fd_sc_hd__nor2_1 g8941(.A (n_60), .B (n_371), .Y (n_131));
  sky130_fd_sc_hd__nand3_1 g8945(.A (n_371), .B (n_480), .C (n_59), .Y
       (n_127));
  sky130_fd_sc_hd__o221ai_1 g8946(.A1 (n_27), .A2 (n_3), .B1 (n_13),
       .B2 (n_53), .C1 (n_120), .Y (n_126));
  sky130_fd_sc_hd__nand2_1 g8951(.A (n_433), .B (n_11), .Y (n_121));
  sky130_fd_sc_hd__a21oi_1 g8952(.A1 (n_65), .A2 (n_18), .B1 (n_464),
       .Y (n_120));
  sky130_fd_sc_hd__a41oi_1 g8956(.A1 (n_54), .A2 (n_81), .A3 (n_231),
       .A4 (n_13), .B1 (n_103), .Y (n_115));
  sky130_fd_sc_hd__a21oi_2 g8957(.A1 (n_2), .A2 (n_426), .B1 (n_101),
       .Y (n_114));
  sky130_fd_sc_hd__o32a_1 g8958(.A1 (n_430), .A2 (n_10), .A3 (n_375),
       .B1 (n_374), .B2 (n_84), .X (n_113));
  sky130_fd_sc_hd__a21o_1 g8966(.A1 (n_428), .A2 (n_60), .B1 (n_409),
       .X (n_106));
  sky130_fd_sc_hd__o22ai_1 g8969(.A1 (n_13), .A2 (n_84), .B1 (n_430),
       .B2 (n_408), .Y (n_103));
  sky130_fd_sc_hd__nor4_2 g8971(.A (n_9), .B (n_63), .C (n_76), .D
       (n_482), .Y (n_101));
  sky130_fd_sc_hd__mux2_2 g8974(.A0 (n_80), .A1 (n_430), .S (n_19), .X
       (n_98));
  sky130_fd_sc_hd__or2_1 g8981(.A (n_11), .B (n_84), .X (n_92));
  sky130_fd_sc_hd__inv_2 g8983(.A (n_90), .Y (n_91));
  sky130_fd_sc_hd__nor2b_1 g8984(.A (n_41), .B_N (n_360), .Y (n_88));
  sky130_fd_sc_hd__nand2_2 g8985(.A (n_394), .B (n_12), .Y (n_90));
  sky130_fd_sc_hd__inv_2 g8988(.A (n_482), .Y (n_81));
  sky130_fd_sc_hd__nand2_1 g8990(.A (n_51), .B (n_41), .Y (n_77));
  sky130_fd_sc_hd__a21oi_1 g8992(.A1 (n_9), .A2 (n_39), .B1 (n_63), .Y
       (n_85));
  sky130_fd_sc_hd__nand2_1 g8993(.A (n_64), .B (n_206), .Y (n_84));
  sky130_fd_sc_hd__nand2b_4 g8996(.A_N (n_315), .B (n_64), .Y (n_80));
  sky130_fd_sc_hd__a2bb2oi_1 g9001(.A1_N (n_13), .A2_N (n_27), .B1
       (n_375), .B2 (n_39), .Y (n_70));
  sky130_fd_sc_hd__a21boi_1 g9002(.A1 (n_9), .A2 (n_41), .B1_N (n_0),
       .Y (n_69));
  sky130_fd_sc_hd__nand2_1 g9003(.A (n_57), .B (n_1), .Y (n_76));
  sky130_fd_sc_hd__clkinv_1 g9010(.A (n_60), .Y (n_59));
  sky130_fd_sc_hd__nand2_2 g9011(.A (n_207), .B (n_32), .Y (n_58));
  sky130_fd_sc_hd__nand2_1 g9013(.A (n_380), .B (n_40), .Y (n_57));
  sky130_fd_sc_hd__nand2_1 g9015(.A (op[2]), .B (op[1]), .Y (n_66));
  sky130_fd_sc_hd__nor2_1 g9016(.A (n_374), .B (n_28), .Y (n_65));
  sky130_fd_sc_hd__and2_4 g9017(.A (n_43), .B (op[2]), .X (n_64));
  sky130_fd_sc_hd__nand2_1 g9018(.A (n_42), .B (n_32), .Y (n_63));
  sky130_fd_sc_hd__or2_2 g9020(.A (op[2]), .B (op[1]), .X (n_60));
  sky130_fd_sc_hd__inv_2 g9022(.A (n_53), .Y (n_54));
  sky130_fd_sc_hd__buf_1 g9023(.A (n_359), .X (n_53));
  sky130_fd_sc_hd__inv_2 g9024(.A (n_359), .Y (n_51));
  sky130_fd_sc_hd__nand2_1 g9025(.A (n_315), .B (n_40), .Y (n_50));
  sky130_fd_sc_hd__nand2_1 g9031(.A (n_22), .B (n_380), .Y (n_45));
  sky130_fd_sc_hd__inv_1 g9036(.A (op[1]), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g9039(.A (n_42), .Y (n_19));
  sky130_fd_sc_hd__inv_1 g9040(.A (b[3]), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g9041(.A (a[3]), .Y (n_41));
  sky130_fd_sc_hd__inv_2 g9042(.A (n_40), .Y (n_39));
  sky130_fd_sc_hd__inv_2 g9043(.A (b[0]), .Y (n_40));
  sky130_fd_sc_hd__inv_4 g9048(.A (n_38), .Y (n_18));
  sky130_fd_sc_hd__inv_2 g9049(.A (b[0]), .Y (n_38));
  sky130_fd_sc_hd__inv_2 g9064(.A (op[2]), .Y (n_33));
  sky130_fd_sc_hd__inv_2 g9065(.A (b[2]), .Y (n_32));
  sky130_fd_sc_hd__clkbuf_1 g9067(.A (a[0]), .X (n_13));
  sky130_fd_sc_hd__inv_2 g9069(.A (n_30), .Y (n_31));
  sky130_fd_sc_hd__clkinv_1 g9070(.A (a[2]), .Y (n_30));
  sky130_fd_sc_hd__inv_2 g9073(.A (n_11), .Y (n_12));
  sky130_fd_sc_hd__buf_1 g9075(.A (a[2]), .X (n_11));
  sky130_fd_sc_hd__inv_2 g9078(.A (n_27), .Y (n_28));
  sky130_fd_sc_hd__inv_2 g9079(.A (n_26), .Y (n_27));
  sky130_fd_sc_hd__inv_2 g9081(.A (n_25), .Y (n_26));
  sky130_fd_sc_hd__inv_2 g9082(.A (n_339), .Y (n_25));
  sky130_fd_sc_hd__inv_2 g9087(.A (n_10), .Y (n_9));
  sky130_fd_sc_hd__inv_1 g9088(.A (n_22), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g9089(.A (n_338), .Y (n_22));
  sky130_fd_sc_hd__nand2b_1 g9114(.A_N (b[3]), .B (n_470), .Y (n_4));
  sky130_fd_sc_hd__mux2i_1 g9115(.A0 (n_30), .A1 (n_41), .S (n_18), .Y
       (n_3));
  sky130_fd_sc_hd__xor2_1 g9116(.A (n_375), .B (n_27), .X (n_2));
  sky130_fd_sc_hd__nand2b_1 g9117(.A_N (a[0]), .B (n_18), .Y (n_1));
  sky130_fd_sc_hd__nand2b_1 g9118(.A_N (a[2]), .B (n_18), .Y (n_0));
  sky130_fd_sc_hd__nand3_1 g3(.A (n_40), .B (a[1]), .C (n_22), .Y
       (n_191));
  sky130_fd_sc_hd__inv_2 fopt9136(.A (n_315), .Y (n_199));
  sky130_fd_sc_hd__inv_1 fopt9141(.A (n_207), .Y (n_206));
  sky130_fd_sc_hd__clkinv_2 fopt9142(.A (n_476), .Y (n_207));
  sky130_fd_sc_hd__inv_2 g9170(.A (n_63), .Y (n_231));
  sky130_fd_sc_hd__nand2_1 g1(.A (n_371), .B (n_473), .Y (n_246));
  sky130_fd_sc_hd__nand3_1 g22(.A (n_352), .B (n_282), .C (a[1]), .Y
       (n_283));
  sky130_fd_sc_hd__nand2_2 g24(.A (n_392), .B (n_22), .Y (n_282));
  sky130_fd_sc_hd__nand2_1 g56(.A (n_337), .B (n_302), .Y (n_290));
  sky130_fd_sc_hd__nand2_1 g58(.A (n_287), .B (n_415), .Y (n_288));
  sky130_fd_sc_hd__inv_1 g60(.A (n_397), .Y (n_287));
  sky130_fd_sc_hd__nand3_1 g258(.A (n_371), .B (n_132), .C (n_91), .Y
       (n_292));
  sky130_fd_sc_hd__inv_1 g260(.A (n_88), .Y (n_295));
  sky130_fd_sc_hd__nand3_1 g9225(.A (n_288), .B (n_301), .C (n_59), .Y
       (n_302));
  sky130_fd_sc_hd__nand2_1 g9226(.A (n_397), .B (n_414), .Y (n_301));
  sky130_fd_sc_hd__a21oi_1 g306(.A1 (n_76), .A2 (n_9), .B1 (n_482), .Y
       (n_304));
  sky130_fd_sc_hd__clkinv_1 g308(.A (n_0), .Y (n_305));
  sky130_fd_sc_hd__nand3_1 g218(.A (n_315), .B (n_347), .C (n_45), .Y
       (n_316));
  sky130_fd_sc_hd__nand4_1 g129(.A (n_304), .B (n_318), .C (n_77), .D
       (n_231), .Y (n_319));
  sky130_fd_sc_hd__nand2b_1 g130(.A_N (n_26), .B (n_305), .Y (n_318));
  sky130_fd_sc_hd__nand3_1 g64(.A (n_460), .B (n_319), .C (n_322), .Y
       (n_323));
  sky130_fd_sc_hd__or2_1 g65(.A (a[3]), .B (n_84), .X (n_322));
  sky130_fd_sc_hd__inv_1 g206(.A (n_325), .Y (n_326));
  sky130_fd_sc_hd__nand2_1 g207(.A (n_292), .B (n_295), .Y (n_325));
  sky130_fd_sc_hd__and2_1 g9229(.A (n_330), .B (n_31), .X (n_331));
  sky130_fd_sc_hd__nand2_1 g19(.A (n_50), .B (n_408), .Y (n_330));
  sky130_fd_sc_hd__clkbuf_1 g9230(.A (n_330), .X (n_332));
  sky130_fd_sc_hd__nor2_2 g9231(.A (n_334), .B (n_336), .Y (n_337));
  sky130_fd_sc_hd__nand3_1 g9232(.A (n_333), .B (n_92), .C (n_465), .Y
       (n_334));
  sky130_fd_sc_hd__o2111ai_1 g9233(.A1 (n_11), .A2 (n_359), .B1 (n_81),
       .C1 (n_85), .D1 (n_70), .Y (n_333));
  sky130_fd_sc_hd__nand2_1 g9234(.A (n_335), .B (n_121), .Y (n_336));
  sky130_fd_sc_hd__nand2_1 g67(.A (n_435), .B (b[2]), .Y (n_335));
  sky130_fd_sc_hd__inv_2 g9236(.A (n_339), .Y (n_340));
  sky130_fd_sc_hd__inv_2 g9237(.A (n_338), .Y (n_339));
  sky130_fd_sc_hd__inv_2 g9238(.A (b[1]), .Y (n_338));
  sky130_fd_sc_hd__clkinv_1 g13(.A (n_473), .Y (n_345));
  sky130_fd_sc_hd__nand2_1 g37(.A (n_348), .B (n_199), .Y (n_349));
  sky130_fd_sc_hd__nand2_1 g38(.A (n_347), .B (n_45), .Y (n_348));
  sky130_fd_sc_hd__nand2_1 g39(.A (n_340), .B (a[1]), .Y (n_347));
  sky130_fd_sc_hd__nand2_1 g8(.A (n_470), .B (n_340), .Y (n_352));
  sky130_fd_sc_hd__nand3_1 g50(.A (n_206), .B (n_25), .C (n_40), .Y
       (n_354));
  sky130_fd_sc_hd__nand2_2 g51(.A (n_25), .B (n_40), .Y (n_359));
  sky130_fd_sc_hd__nand2_2 g17(.A (n_360), .B (n_41), .Y (n_361));
  sky130_fd_sc_hd__nand2_2 g18(.A (n_369), .B (n_4), .Y (n_360));
  sky130_fd_sc_hd__nand2_4 g9243(.A (n_370), .B (n_361), .Y (n_371));
  sky130_fd_sc_hd__nand3_1 g25(.A (n_369), .B (n_4), .C (a[3]), .Y
       (n_370));
  sky130_fd_sc_hd__nand2_1 g26(.A (n_392), .B (b[3]), .Y (n_369));
  sky130_fd_sc_hd__inv_2 fopt9245(.A (n_375), .Y (n_374));
  sky130_fd_sc_hd__inv_2 fopt9248(.A (a[1]), .Y (n_375));
  sky130_fd_sc_hd__inv_2 fopt9252(.A (a[1]), .Y (n_380));
  sky130_fd_sc_hd__nand4_1 g57(.A (n_388), .B (n_134), .C (n_137), .D
       (n_345), .Y (n_389));
  sky130_fd_sc_hd__nand3_2 g9255(.A (n_387), .B (n_91), .C (n_332), .Y
       (n_388));
  sky130_fd_sc_hd__nand2_4 g59(.A (n_475), .B (n_283), .Y (n_387));
  sky130_fd_sc_hd__clkinv_2 g4(.A (n_470), .Y (n_392));
  sky130_fd_sc_hd__nand2_1 g9256(.A (n_396), .B (n_90), .Y (n_397));
  sky130_fd_sc_hd__nand2_1 g9257(.A (n_395), .B (n_11), .Y (n_396));
  sky130_fd_sc_hd__inv_2 g27(.A (n_395), .Y (n_394));
  sky130_fd_sc_hd__nand3_2 g9259(.A (n_410), .B (n_474), .C (n_481), .Y
       (n_414));
  sky130_fd_sc_hd__nand2_1 g53(.A (n_407), .B (n_409), .Y (n_410));
  sky130_fd_sc_hd__nand2_1 g9260(.A (n_349), .B (n_316), .Y (n_407));
  sky130_fd_sc_hd__inv_1 g9261(.A (n_408), .Y (n_409));
  sky130_fd_sc_hd__nand2_2 g9262(.A (n_18), .B (a[0]), .Y (n_408));
  sky130_fd_sc_hd__clkinv_1 g9264(.A (n_414), .Y (n_415));
  sky130_fd_sc_hd__inv_1 fopt(.A (n_80), .Y (n_426));
  sky130_fd_sc_hd__clkbuf_1 fopt9266(.A (n_80), .X (n_428));
  sky130_fd_sc_hd__nand2_2 g9267(.A (n_33), .B (op[1]), .Y (n_430));
  sky130_fd_sc_hd__o21ai_1 g9268(.A1 (b[2]), .A2 (n_428), .B1 (n_436),
       .Y (n_433));
  sky130_fd_sc_hd__o221ai_1 g9272(.A1 (n_11), .A2 (n_80), .B1 (n_12),
       .B2 (n_430), .C1 (n_436), .Y (n_435));
  sky130_fd_sc_hd__o2bb2ai_1 g9273(.A1_N (n_436), .A2_N (n_106), .B1
       (n_13), .B2 (n_18), .Y (n_437));
  sky130_fd_sc_hd__o2111a_1 g9275(.A1 (n_65), .A2 (n_436), .B1 (n_113),
       .C1 (n_468), .D1 (n_114), .X (n_438));
  sky130_fd_sc_hd__o211ai_2 g9276(.A1 (n_53), .A2 (n_464), .B1 (n_436),
       .C1 (n_98), .Y (n_439));
  sky130_fd_sc_hd__a21oi_2 g9288(.A1 (n_439), .A2 (a[3]), .B1 (n_323),
       .Y (n_451));
  sky130_fd_sc_hd__nand3_1 g23(.A (n_154), .B (n_451), .C (n_453), .Y
       (n_454));
  sky130_fd_sc_hd__a21o_1 g9289(.A1 (n_397), .A2 (n_414), .B1 (n_127),
       .X (n_453));
  sky130_fd_sc_hd__a41oi_2 g94(.A1 (n_326), .A2 (n_147), .A3 (n_246),
       .A4 (n_455), .B1 (n_60), .Y (n_456));
  sky130_fd_sc_hd__nand3_1 g95(.A (n_387), .B (n_371), .C (n_331), .Y
       (n_455));
  sky130_fd_sc_hd__or2_4 g9290(.A (n_430), .B (n_199), .X (n_436));
  sky130_fd_sc_hd__nand2_1 g21(.A (n_483), .B (n_19), .Y (n_460));
  sky130_fd_sc_hd__inv_2 g71(.A (n_461), .Y (n_315));
  sky130_fd_sc_hd__inv_2 g74(.A (op[0]), .Y (n_461));
  sky130_fd_sc_hd__nand2_1 g9292(.A (n_231), .B (n_463), .Y (n_464));
  sky130_fd_sc_hd__nor2_1 g70(.A (n_315), .B (n_66), .Y (n_463));
  sky130_fd_sc_hd__nand4bb_1 g9293(.A_N (n_28), .B_N (n_63), .C (n_3),
       .D (n_463), .Y (n_465));
  sky130_fd_sc_hd__nand3_1 g66(.A (n_85), .B (n_69), .C (n_467), .Y
       (n_468));
  sky130_fd_sc_hd__nor2b_1 g68(.A (n_466), .B_N (n_463), .Y (n_467));
  sky130_fd_sc_hd__nor2_1 g69(.A (n_374), .B (n_359), .Y (n_466));
  sky130_fd_sc_hd__inv_2 g73(.A (n_461), .Y (n_470));
  sky130_fd_sc_hd__nand2_1 g9294(.A (n_472), .B (n_480), .Y (n_473));
  sky130_fd_sc_hd__nand3_1 g42(.A (n_471), .B (n_374), .C (n_31), .Y
       (n_472));
  sky130_fd_sc_hd__nand2_2 g43(.A (n_352), .B (n_282), .Y (n_471));
  sky130_fd_sc_hd__nand2_2 g40(.A (n_471), .B (n_374), .Y (n_474));
  sky130_fd_sc_hd__nand2_2 g41(.A (n_471), .B (n_380), .Y (n_475));
  sky130_fd_sc_hd__inv_2 g9295(.A (n_461), .Y (n_476));
  sky130_fd_sc_hd__nand2_2 g9296(.A (n_477), .B (n_58), .Y (n_395));
  sky130_fd_sc_hd__nand2_1 g9297(.A (n_476), .B (b[2]), .Y (n_477));
  sky130_fd_sc_hd__nand3_1 g9298(.A (n_477), .B (n_58), .C (n_31), .Y
       (n_480));
  sky130_fd_sc_hd__and2_1 g2(.A (n_191), .B (n_354), .X (n_481));
  sky130_fd_sc_hd__nand2b_1 g9300(.A_N (n_66), .B (n_315), .Y (n_482));
  sky130_fd_sc_hd__o22ai_1 g9301(.A1 (a[3]), .A2 (n_80), .B1 (n_430),
       .B2 (n_199), .Y (n_483));
endmodule

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [2:0] op_reg;
  wire carry_reg_48, \result_reg[0]_36 , \result_reg[1]_37 ,
       \result_reg[2]_38 , \result_reg[3]_39 ;
  alu alu_design(.clk (clk), .rst_n (rst_n), .a (a_reg), .b (b_reg),
       .op (op_reg), .result ({\result_reg[3]_39 , \result_reg[2]_38 ,
       \result_reg[1]_37 , \result_reg[0]_36 }), .carry (carry_reg_48));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_39 ), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_38 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_36 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_48), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_37 ), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op[2]), .Q (op_reg[2]));
  sky130_fd_sc_hd__dfrtp_2 \a_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (a[1]), .Q (a_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op[0]), .Q (op_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (a[0]), .Q (a_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op[1]), .Q (op_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (a[2]), .Q (a_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (a[3]), .Q (a_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (b[2]), .Q (b_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (b[0]), .Q (b_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (b[3]), .Q (b_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (b[1]), .Q (b_reg[1]));
endmodule

