
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 17 2025 03:12:48

// Verification Directory fv/synth_wrapper 

module alu(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_159), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_158), .Q (result[2]));
  sky130_fd_sc_hd__nand3_1 g8907(.A (n_154), .B (n_155), .C (n_141), .Y
       (n_159));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (n_156), .Q (carry));
  sky130_fd_sc_hd__nand2_1 g8909(.A (n_157), .B (n_144), .Y (n_158));
  sky130_fd_sc_hd__nand2_1 g8910(.A (n_151), .B (n_59), .Y (n_157));
  sky130_fd_sc_hd__a41oi_1 g8911(.A1 (n_149), .A2 (n_150), .A3 (n_147),
       .A4 (n_148), .B1 (n_60), .Y (n_156));
  sky130_fd_sc_hd__a21o_1 g8912(.A1 (n_8), .A2 (n_111), .B1 (n_127), .X
       (n_155));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_152), .Q (result[1]));
  sky130_fd_sc_hd__nand2_1 g8914(.A (n_153), .B (n_131), .Y (n_154));
  sky130_fd_sc_hd__nand4_1 g8915(.A (n_133), .B (n_6), .C (n_137), .D
       (n_134), .Y (n_153));
  sky130_fd_sc_hd__o21ai_2 g8916(.A1 (n_60), .A2 (n_142), .B1 (n_136),
       .Y (n_152));
  sky130_fd_sc_hd__o2bb2ai_1 g8917(.A1_N (n_111), .A2_N (n_7), .B1
       (n_111), .B2 (n_7), .Y (n_151));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_143), .Q (result[0]));
  sky130_fd_sc_hd__a31oi_1 g8919(.A1 (n_104), .A2 (n_91), .A3 (n_132),
       .B1 (n_88), .Y (n_150));
  sky130_fd_sc_hd__nor2_1 g8920(.A (n_130), .B (n_146), .Y (n_149));
  sky130_fd_sc_hd__nand3_1 g8922(.A (n_5), .B (n_104), .C (n_118), .Y
       (n_148));
  sky130_fd_sc_hd__nand4_1 g8923(.A (n_118), .B (n_104), .C (n_83), .D
       (n_91), .Y (n_147));
  sky130_fd_sc_hd__nor2_1 g8925(.A (n_140), .B (n_124), .Y (n_146));
  sky130_fd_sc_hd__a21oi_1 g8927(.A1 (n_123), .A2 (b[2]), .B1 (n_138),
       .Y (n_144));
  sky130_fd_sc_hd__nand3_1 g8928(.A (n_128), .B (n_115), .C (n_126), .Y
       (n_143));
  sky130_fd_sc_hd__xnor2_2 g8929(.A (n_83), .B (n_118), .Y (n_142));
  sky130_fd_sc_hd__a21oi_2 g8930(.A1 (n_129), .A2 (a[3]), .B1 (n_135),
       .Y (n_141));
  sky130_fd_sc_hd__nand3_2 g8931(.A (n_112), .B (n_139), .C (n_117), .Y
       (n_145));
  sky130_fd_sc_hd__nand2_2 g8932(.A (n_125), .B (n_55), .Y (n_139));
  sky130_fd_sc_hd__nand4_1 g8933(.A (n_121), .B (n_116), .C (n_92), .D
       (n_100), .Y (n_138));
  sky130_fd_sc_hd__nand4_1 g8934(.A (n_73), .B (n_75), .C (n_31), .D
       (n_37), .Y (n_140));
  sky130_fd_sc_hd__nand2_1 g8935(.A (n_91), .B (n_132), .Y (n_137));
  sky130_fd_sc_hd__o2111a_1 g8936(.A1 (n_65), .A2 (n_78), .B1 (n_113),
       .C1 (n_108), .D1 (n_114), .X (n_136));
  sky130_fd_sc_hd__o211ai_2 g8937(.A1 (a[3]), .A2 (n_84), .B1 (n_119),
       .C1 (n_122), .Y (n_135));
  sky130_fd_sc_hd__nand2_2 g8938(.A (n_5), .B (n_118), .Y (n_134));
  sky130_fd_sc_hd__nand3_1 g8939(.A (n_118), .B (n_91), .C (n_83), .Y
       (n_133));
  sky130_fd_sc_hd__inv_2 g8940(.A (n_112), .Y (n_132));
  sky130_fd_sc_hd__nor2_1 g8941(.A (n_60), .B (n_104), .Y (n_131));
  sky130_fd_sc_hd__nor2_1 g8942(.A (n_89), .B (n_124), .Y (n_130));
  sky130_fd_sc_hd__o211ai_1 g8943(.A1 (n_53), .A2 (n_95), .B1 (n_78),
       .C1 (n_98), .Y (n_129));
  sky130_fd_sc_hd__o2bb2ai_1 g8944(.A1_N (n_78), .A2_N (n_106), .B1
       (n_13), .B2 (n_18), .Y (n_128));
  sky130_fd_sc_hd__nand3_1 g8945(.A (n_104), .B (n_89), .C (n_59), .Y
       (n_127));
  sky130_fd_sc_hd__o221ai_1 g8946(.A1 (n_29), .A2 (n_3), .B1 (n_13),
       .B2 (n_53), .C1 (n_120), .Y (n_126));
  sky130_fd_sc_hd__o2bb2ai_2 g8947(.A1_N (n_34), .A2_N (n_105), .B1
       (n_34), .B2 (n_105), .Y (n_125));
  sky130_fd_sc_hd__inv_2 g8948(.A (n_104), .Y (n_124));
  sky130_fd_sc_hd__o221ai_1 g8949(.A1 (n_11), .A2 (n_80), .B1 (n_12),
       .B2 (n_61), .C1 (n_78), .Y (n_123));
  sky130_fd_sc_hd__nand2_1 g8950(.A (n_99), .B (n_19), .Y (n_122));
  sky130_fd_sc_hd__nand2_1 g8951(.A (n_97), .B (n_11), .Y (n_121));
  sky130_fd_sc_hd__a21oi_1 g8952(.A1 (n_65), .A2 (n_18), .B1 (n_95), .Y
       (n_120));
  sky130_fd_sc_hd__o2111ai_1 g8953(.A1 (n_26), .A2 (n_0), .B1 (n_62),
       .C1 (n_77), .D1 (n_107), .Y (n_119));
  sky130_fd_sc_hd__nor2_2 g8954(.A (n_102), .B (n_71), .Y (n_117));
  sky130_fd_sc_hd__o2111ai_1 g8955(.A1 (n_11), .A2 (n_52), .B1 (n_81),
       .C1 (n_70), .D1 (n_85), .Y (n_116));
  sky130_fd_sc_hd__a41oi_1 g8956(.A1 (n_54), .A2 (n_81), .A3 (n_62),
       .A4 (n_13), .B1 (n_103), .Y (n_115));
  sky130_fd_sc_hd__a21oi_2 g8957(.A1 (n_2), .A2 (n_79), .B1 (n_101), .Y
       (n_114));
  sky130_fd_sc_hd__o32a_1 g8958(.A1 (n_61), .A2 (n_10), .A3 (n_15), .B1
       (n_16), .B2 (n_84), .X (n_113));
  sky130_fd_sc_hd__nand2_4 g8959(.A (n_109), .B (n_110), .Y (n_118));
  sky130_fd_sc_hd__nand2_2 g8961(.A (n_73), .B (n_17), .Y (n_110));
  sky130_fd_sc_hd__nand2_4 g8962(.A (n_96), .B (n_37), .Y (n_109));
  sky130_fd_sc_hd__o2111ai_1 g8964(.A1 (n_14), .A2 (n_52), .B1 (n_86),
       .C1 (n_69), .D1 (n_85), .Y (n_108));
  sky130_fd_sc_hd__a21oi_1 g8965(.A1 (n_76), .A2 (n_9), .B1 (n_82), .Y
       (n_107));
  sky130_fd_sc_hd__a21o_1 g8966(.A1 (n_80), .A2 (n_60), .B1 (n_55), .X
       (n_106));
  sky130_fd_sc_hd__nand2_1 g8967(.A (n_73), .B (n_16), .Y (n_112));
  sky130_fd_sc_hd__nand2_1 g8968(.A (n_90), .B (n_87), .Y (n_111));
  sky130_fd_sc_hd__o22ai_1 g8969(.A1 (n_13), .A2 (n_84), .B1 (n_61),
       .B2 (n_56), .Y (n_103));
  sky130_fd_sc_hd__and4_4 g8970(.A (n_40), .B (n_14), .C (op[0]), .D
       (n_22), .X (n_102));
  sky130_fd_sc_hd__nor4_2 g8971(.A (n_9), .B (n_63), .C (n_76), .D
       (n_82), .Y (n_101));
  sky130_fd_sc_hd__nand3b_1 g8972(.A_N (n_95), .B (n_3), .C (n_29), .Y
       (n_100));
  sky130_fd_sc_hd__o21ai_1 g8973(.A1 (a[3]), .A2 (n_80), .B1 (n_78), .Y
       (n_99));
  sky130_fd_sc_hd__mux2_2 g8974(.A0 (n_80), .A1 (n_61), .S (n_19), .X
       (n_98));
  sky130_fd_sc_hd__o21ai_1 g8975(.A1 (b[2]), .A2 (n_80), .B1 (n_78), .Y
       (n_97));
  sky130_fd_sc_hd__nand2_2 g8976(.A (n_49), .B (n_45), .Y (n_105));
  sky130_fd_sc_hd__nand2_4 g8977(.A (n_93), .B (n_94), .Y (n_104));
  sky130_fd_sc_hd__inv_2 g8978(.A (n_73), .Y (n_96));
  sky130_fd_sc_hd__nand3_1 g8979(.A (n_68), .B (n_4), .C (a[3]), .Y
       (n_94));
  sky130_fd_sc_hd__nand2_2 g8980(.A (n_72), .B (n_41), .Y (n_93));
  sky130_fd_sc_hd__or2_1 g8981(.A (n_11), .B (n_84), .X (n_92));
  sky130_fd_sc_hd__nand2_1 g8982(.A (n_86), .B (n_62), .Y (n_95));
  sky130_fd_sc_hd__inv_2 g8983(.A (n_90), .Y (n_91));
  sky130_fd_sc_hd__nor2b_1 g8984(.A (n_41), .B_N (n_72), .Y (n_88));
  sky130_fd_sc_hd__nand2_1 g8985(.A (n_74), .B (n_12), .Y (n_90));
  sky130_fd_sc_hd__nand2_1 g8986(.A (n_75), .B (n_11), .Y (n_87));
  sky130_fd_sc_hd__nand2b_2 g8987(.A_N (n_75), .B (n_31), .Y (n_89));
  sky130_fd_sc_hd__inv_2 g8988(.A (n_82), .Y (n_81));
  sky130_fd_sc_hd__inv_1 g8989(.A (n_80), .Y (n_79));
  sky130_fd_sc_hd__nand2_1 g8990(.A (n_51), .B (n_41), .Y (n_77));
  sky130_fd_sc_hd__nor2_1 g8991(.A (op[0]), .B (n_66), .Y (n_86));
  sky130_fd_sc_hd__a21oi_1 g8992(.A1 (n_9), .A2 (n_39), .B1 (n_63), .Y
       (n_85));
  sky130_fd_sc_hd__nand2_2 g8993(.A (n_64), .B (op[0]), .Y (n_84));
  sky130_fd_sc_hd__nand2_2 g8994(.A (n_50), .B (n_56), .Y (n_83));
  sky130_fd_sc_hd__nand2_1 g8995(.A (op[0]), .B (n_67), .Y (n_82));
  sky130_fd_sc_hd__nand2b_4 g8996(.A_N (op[0]), .B (n_64), .Y (n_80));
  sky130_fd_sc_hd__or2_4 g8997(.A (n_61), .B (n_34), .X (n_78));
  sky130_fd_sc_hd__inv_1 g8998(.A (n_75), .Y (n_74));
  sky130_fd_sc_hd__nor2_1 g9000(.A (n_44), .B (n_52), .Y (n_71));
  sky130_fd_sc_hd__a2bb2oi_1 g9001(.A1_N (n_13), .A2_N (n_27), .B1
       (n_17), .B2 (n_39), .Y (n_70));
  sky130_fd_sc_hd__a21boi_1 g9002(.A1 (n_9), .A2 (n_41), .B1_N (n_0),
       .Y (n_69));
  sky130_fd_sc_hd__nand2_1 g9003(.A (n_57), .B (n_1), .Y (n_76));
  sky130_fd_sc_hd__nand2_2 g9005(.A (n_58), .B (n_46), .Y (n_75));
  sky130_fd_sc_hd__nand2_2 g9006(.A (n_48), .B (n_47), .Y (n_73));
  sky130_fd_sc_hd__nand2_1 g9007(.A (n_68), .B (n_4), .Y (n_72));
  sky130_fd_sc_hd__inv_2 g9008(.A (n_66), .Y (n_67));
  sky130_fd_sc_hd__inv_2 g9009(.A (n_63), .Y (n_62));
  sky130_fd_sc_hd__clkinv_1 g9010(.A (n_60), .Y (n_59));
  sky130_fd_sc_hd__nand2_2 g9011(.A (n_34), .B (n_32), .Y (n_58));
  sky130_fd_sc_hd__nand2_1 g9013(.A (n_17), .B (n_40), .Y (n_57));
  sky130_fd_sc_hd__nand2_1 g9014(.A (n_34), .B (b[3]), .Y (n_68));
  sky130_fd_sc_hd__nand2_1 g9015(.A (op[2]), .B (op[1]), .Y (n_66));
  sky130_fd_sc_hd__nor2_1 g9016(.A (n_14), .B (n_28), .Y (n_65));
  sky130_fd_sc_hd__and2_4 g9017(.A (n_43), .B (op[2]), .X (n_64));
  sky130_fd_sc_hd__nand2_1 g9018(.A (n_42), .B (n_32), .Y (n_63));
  sky130_fd_sc_hd__nand2_1 g9019(.A (n_33), .B (op[1]), .Y (n_61));
  sky130_fd_sc_hd__or2_1 g9020(.A (op[2]), .B (op[1]), .X (n_60));
  sky130_fd_sc_hd__clkinv_1 g9021(.A (n_56), .Y (n_55));
  sky130_fd_sc_hd__inv_2 g9022(.A (n_53), .Y (n_54));
  sky130_fd_sc_hd__buf_1 g9023(.A (n_52), .X (n_53));
  sky130_fd_sc_hd__inv_2 g9024(.A (n_52), .Y (n_51));
  sky130_fd_sc_hd__nand2_1 g9025(.A (op[0]), .B (n_40), .Y (n_50));
  sky130_fd_sc_hd__nand2_2 g9026(.A (n_24), .B (a[1]), .Y (n_49));
  sky130_fd_sc_hd__nand2_1 g9027(.A (n_34), .B (n_22), .Y (n_48));
  sky130_fd_sc_hd__nand2_1 g9029(.A (op[0]), .B (n_24), .Y (n_47));
  sky130_fd_sc_hd__nand2_1 g9030(.A (op[0]), .B (b[2]), .Y (n_46));
  sky130_fd_sc_hd__nand2_1 g9031(.A (n_22), .B (n_35), .Y (n_45));
  sky130_fd_sc_hd__nand2_1 g9032(.A (n_15), .B (op[0]), .Y (n_44));
  sky130_fd_sc_hd__nand2_2 g9034(.A (n_18), .B (a[0]), .Y (n_56));
  sky130_fd_sc_hd__nand2_2 g9035(.A (n_25), .B (n_40), .Y (n_52));
  sky130_fd_sc_hd__inv_1 g9036(.A (op[1]), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g9039(.A (n_42), .Y (n_19));
  sky130_fd_sc_hd__inv_2 g9040(.A (b[3]), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g9041(.A (a[3]), .Y (n_41));
  sky130_fd_sc_hd__inv_2 g9042(.A (n_40), .Y (n_39));
  sky130_fd_sc_hd__inv_2 g9043(.A (b[0]), .Y (n_40));
  sky130_fd_sc_hd__inv_4 g9048(.A (n_38), .Y (n_18));
  sky130_fd_sc_hd__inv_2 g9049(.A (b[0]), .Y (n_38));
  sky130_fd_sc_hd__inv_2 g9053(.A (a[1]), .Y (n_17));
  sky130_fd_sc_hd__inv_2 g9056(.A (n_15), .Y (n_16));
  sky130_fd_sc_hd__clkinv_1 g9057(.A (a[1]), .Y (n_15));
  sky130_fd_sc_hd__inv_2 g9059(.A (n_36), .Y (n_37));
  sky130_fd_sc_hd__inv_2 g9060(.A (n_14), .Y (n_36));
  sky130_fd_sc_hd__inv_2 g9061(.A (n_35), .Y (n_14));
  sky130_fd_sc_hd__inv_2 g9062(.A (a[1]), .Y (n_35));
  sky130_fd_sc_hd__clkinv_8 g9063(.A (op[0]), .Y (n_34));
  sky130_fd_sc_hd__inv_2 g9064(.A (op[2]), .Y (n_33));
  sky130_fd_sc_hd__inv_2 g9065(.A (b[2]), .Y (n_32));
  sky130_fd_sc_hd__clkbuf_1 g9067(.A (a[0]), .X (n_13));
  sky130_fd_sc_hd__inv_2 g9069(.A (n_30), .Y (n_31));
  sky130_fd_sc_hd__clkinv_1 g9070(.A (a[2]), .Y (n_30));
  sky130_fd_sc_hd__inv_2 g9073(.A (n_11), .Y (n_12));
  sky130_fd_sc_hd__buf_1 g9075(.A (a[2]), .X (n_11));
  sky130_fd_sc_hd__inv_2 g9077(.A (n_28), .Y (n_29));
  sky130_fd_sc_hd__inv_2 g9078(.A (n_27), .Y (n_28));
  sky130_fd_sc_hd__inv_4 g9079(.A (n_26), .Y (n_27));
  sky130_fd_sc_hd__inv_2 g9081(.A (n_25), .Y (n_26));
  sky130_fd_sc_hd__inv_2 g9082(.A (n_23), .Y (n_25));
  sky130_fd_sc_hd__clkinv_2 g9083(.A (n_23), .Y (n_24));
  sky130_fd_sc_hd__inv_2 g9084(.A (n_20), .Y (n_23));
  sky130_fd_sc_hd__inv_2 g9087(.A (n_10), .Y (n_9));
  sky130_fd_sc_hd__inv_2 g9088(.A (n_22), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g9089(.A (n_20), .Y (n_22));
  sky130_fd_sc_hd__inv_2 g9090(.A (b[1]), .Y (n_20));
  sky130_fd_sc_hd__inv_1 fopt(.A (n_7), .Y (n_8));
  sky130_fd_sc_hd__inv_2 fopt9101(.A (n_145), .Y (n_7));
  sky130_fd_sc_hd__and2_1 g2(.A (n_140), .B (n_89), .X (n_6));
  sky130_fd_sc_hd__and3_1 g9113(.A (n_83), .B (n_75), .C (n_31), .X
       (n_5));
  sky130_fd_sc_hd__nand2b_1 g9114(.A_N (b[3]), .B (op[0]), .Y (n_4));
  sky130_fd_sc_hd__mux2i_1 g9115(.A0 (n_30), .A1 (n_41), .S (n_18), .Y
       (n_3));
  sky130_fd_sc_hd__xor2_1 g9116(.A (n_17), .B (n_27), .X (n_2));
  sky130_fd_sc_hd__nand2b_1 g9117(.A_N (a[0]), .B (n_18), .Y (n_1));
  sky130_fd_sc_hd__nand2b_1 g9118(.A_N (a[2]), .B (n_18), .Y (n_0));
endmodule

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [2:0] op_reg;
  wire carry_reg_48, n_0, \result_reg[0]_36 , \result_reg[1]_37 ,
       \result_reg[2]_38 , \result_reg[3]_39 ;
  alu alu_design(.clk (clk), .rst_n (rst_n), .a (a_reg), .b (b_reg),
       .op ({op_reg[2:1], n_0}), .result ({\result_reg[3]_39 ,
       \result_reg[2]_38 , \result_reg[1]_37 , \result_reg[0]_36 }),
       .carry (carry_reg_48));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_39 ), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_38 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_36 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_48), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_37 ), .Q (result[1]));
  sky130_fd_sc_hd__buf_6 g28(.A (op_reg[0]), .X (n_0));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op[2]), .Q (op_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (a[1]), .Q (a_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op[0]), .Q (op_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (a[0]), .Q (a_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op[1]), .Q (op_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (a[2]), .Q (a_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (a[3]), .Q (a_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (b[2]), .Q (b_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (b[0]), .Q (b_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (b[3]), .Q (b_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (b[1]), .Q (b_reg[1]));
endmodule

